# Homework-2

## Part 1, Working with Numpy
    Your goal is to calculate the final grade for studnets in a class. 
      1. We have 10 Students in class, and 5 assessment score ( Homework, Project, Exam1, Exam2, Final Exam)for each
      student. Create a matrix containing grades of students, (rows are students, columns are assessments). Use for loop and input  function for entering the student name and grades. Enter arbitary grades from 0 to 100 for each assessment 
        2. Create a weight vector containing the weight of each assessment. Example (15%, 15%, 20%, 20%, 30% )
        3. Calculate the final grade for each students. Use Numpy to create your vector, matrix and calculating final grade.
        4. Convert final grades to letter format(90%-100% = A, 80%-89% = B, 70%-79% =C, 60%-69%=D and F for less than 60% )
        5. print out Student names and their grades

## Part 2, Working with Pandas

    - Step 1: Download the titanic.csv file from github.


    - Step 2: Read the file in Python and store it in a dataframe.


    - Step 3: Explore the data in your Jupyter notebook, eg. general info about data, some basic stats.
      Also print out the data for row index 100-105 and columns 'Name', 'Age', 'Fare'


    - Step 4: Create two dataframes, one containing data for only Categorical Variables and one for only Quantitative variable
  
    - Step 5: Write these newly created dataframe in .csv files.

# **Part 1**

In [45]:
import numpy as np

In [68]:
students = ["Aurora", "Ariel", "Moana", "Tiana", "Cinderella", "Mulan", "Belle", "Jasmine", "Rapunzel", "Merida"]
assessments = ["Homework", "Project", "Exam1", "Exam2", "Final"]
grades = np.zeros((10, 5))
weights = np.array([0.15, 0.15, 0.20, 0.20, 0.30])

for i in range(10):
    name = input("Enter student name: ")
    students.append(name)

    print("Enter grades for", name)

    for j in range(5):
        grades[i][j] = float(input(assessments[j] + ": "))

final_grades = grades @ weights
letter_grades = []

for grade in final_grades:
    if grade >= 90:
        letter_grades.append("A")
    elif grade >= 80:
        letter_grades.append("B")
    elif grade >= 70:
        letter_grades.append("C")
    elif grade >= 60:
        letter_grades.append("D")
    else:
        letter_grades.append("F")

        print("\nStudent Grades")
print("-------------------------")

for i in range(10):
    print(students[i], ":", final_grades[i], letter_grades[i])

Enter student name:  Aurora

Enter grades for Aurora

Homework:  95
Project:  88
Exam1:  92
Exam2:  94
Final:  87
Enter student name:  Ariel

Enter grades for Ariel

Homework:  84
Project:  86
Exam1:  77
Exam2:  89
Final:  93
Enter student name:  Moana

Enter grades for Moana

Homework:  100
Project:  92
Exam1:  88
Exam2:  91
Final:  93
Enter student name:  Tiana

Enter grades for Tiana

Homework:  100
Project:  98
Exam1:  96
Exam2:  99
Final:  94
Enter student name:  Cinderella

Enter grades for Cinderella

Homework:  95
Project:  86
Exam1:  91
Exam2:  88
Final:  93
Enter student name:  Mulan

Enter grades for Mulan

Homework:  98
Project:  95
Exam1:  97
Exam2:  99
Final:  100
Enter student name:  Belle

Enter grades for Belle

Homework:  93
Project:  84
Exam1:  92
Exam2:  92
Final:  94
Enter student name:  Jasmine

Enter grades for Jasmine

Homework:  84
Project:  92
Exam1:  88
Exam2:  93
Final:  83
Enter student name:  Rapunzel

Enter grades for Rapunzel

Homework:  97
Project:  83
Exam1:  74
Exam2:  100
Final:  93
Enter student name:  Merida

Enter grades for Merida

Homework:  82
Project:  78
Exam1:  83
Exam2:  85
Final:  88

-------------------------
Aurora : 90.75 A
Ariel : 86.6 B
Moana : 92.5 A
Tiana : 96.89999999999999 A
Cinderella : 90.85 A
Mulan : 98.15 A
Belle : 91.55000000000001 A
Jasmine : 87.5 B
Rapunzel : 89.69999999999999 B
Merida : 84.0 B

# **Part 2**

In [9]:
import numpy as np
import pandas as pd

In [11]:
df = pd.read_csv('titanic.csv')

In [50]:
df.rename(columns={ "PassengerId":"PId","Parch":"ParCh", "Survived":"Surv", "Pclass":"PClass"}, inplace= True)
df.head()

,PId,Surv,PClass,Name,Sex,Age,SibSp,ParCh,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [36]:
df.loc[100:105, ["Name", "Age", "Fare"]]

                                 Name   Age     Fare
100            Petranec, Miss Matilda  28.0   7.8958
101  Petroff, Mr. Pastcho ("Pentcho")   NaN   7.8958
102         White, Mr. Richard Frasar  21.0  77.2875
103        Johansson, Mr. Gustaf Joel  33.0   8.6542
104    Gustafsson, Mr. Anders Vilhelm  37.0   7.9250
105             Mionoff, Mr. Stoytcho  28.0   7.8958

In [60]:
categorical_df = df[["Name", "Sex", "Ticket", "Cabin", "Embarked"]] 
quantitative_df = df[["Age", "PId", "Surv", "PClass", "SibSp", "ParCh", "Fare"]]
display(categorical_df)
display(quantitative_df)

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss Margaret Edith",female,112053,B42,S
888,"Johnston, Miss Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

      Age  PId  Surv  PClass  SibSp  ParCh     Fare
0    22.0    1     0       3      1      0   7.2500
1    38.0    2     1       1      1      0  71.2833
2    26.0    3     1       3      0      0   7.9250
3    35.0    4     1       1      1      0  53.1000
4    35.0    5     0       3      0      0   8.0500
..    ...  ...   ...     ...    ...    ...      ...
886  27.0  887     0       2      0      0  13.0000
887  19.0  888     1       1      0      0  30.0000
888   NaN  889     0       3      1      2  23.4500
889  26.0  890     1       1      0      0  30.0000
890  32.0  891     0       3      0      0   7.7500

[891 rows x 7 columns]

      Age  PId  Surv  PClass  SibSp  ParCh     Fare
0    22.0    1     0       3      1      0   7.2500
1    38.0    2     1       1      1      0  71.2833
2    26.0    3     1       3      0      0   7.9250
3    35.0    4     1       1      1      0  53.1000
4    35.0    5     0       3      0      0   8.0500
..    ...  ...   ...     ...    ...    ...      ...
886  27.0  887     0       2      0      0  13.0000
887  19.0  888     1       1      0      0  30.0000
888   NaN  889     0       3      1      2  23.4500
889  26.0  890     1       1      0      0  30.0000
890  32.0  891     0       3      0      0   7.7500

[891 rows x 7 columns]

In [54]:
categorical_df.to_csv("titanic_categorical.csv", index=False)

In [55]:
quantitative_df.to_csv("titanic_quantitative.csv", index=False)