# Data Science Project 1: Data Wrangling Practical
**Duration:** 1 Hour, 15 Minutes  
**Format:** Open-notes code implementation (Python/Pandas)

### **Project Scenario**
You have been given a raw slice of **Glassdoor Data Science Job Postings**. The dataset contains a variety of small errors, missing variables, and split locations. Your goal is to clean this main dataset, create engineered features, and merge it with a regional mapping file so the analytics team can use it.

## Load the data
Download the data from the Blackboard to your computer frist, then load your libraries and the datasets required for this exam here.

In [97]:
# import all libaries and load your datasets your here
import pandas as pd
import numpy as np
gd = pd.read_csv("glassdoor_jobs.csv")
state_regions_df = pd.read_csv("state_regions.csv")
gd.columns

Index(['Job_Title', 'Job Description', 'Rating', 'Company_Name', 'Location',
       'Founded', 'Industry'],
      dtype='str')

## Part 1: Missing Data & Filtering (30 Points)

### **Task 1.1 (Standardizing Nulls)**
The `Rating` column represents missing values as `-1`. Replace all occurrences of `-1` with the dataset's overall **average (mean)** rating value.

In [98]:
# Write your solution for Task 1.1 here
gd['Rating'] = gd['Rating'].replace(-1, np.nan)
mean_rating = gd['Rating'].mean()
gd['Rating'] = gd['Rating'].fillna(mean_rating)
gd.head(10)

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.100000,Healthfirst\n3.1,"New York, NY",1993,Insurance Carriers
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.200000,ManTech\n4.2,"Chantilly, VA",1968,Research & Development
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,3.885766,Analysis Group\n3.8,"Boston, MA",1981,Consulting
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.500000,INFICON\n3.5,"Newton, MA",2000,Electrical & Electronic Manufacturing
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.900000,Affinity Solutions\n2.9,"New York, NY",1998,Advertising & Marketing
5,Data Scientist,About Us:\n\nHeadquartered in beautiful Santa ...,4.200000,HG Insights\n4.2,"Santa Barbara, CA",2010,NaN
6,Data Scientist / Machine Learning Expert,Posting Title\nData Scientist / Machine Learni...,3.900000,Novartis\n3.9,"Cambridge, MA",1996,Biotech & Pharmaceuticals
7,Data Scientist,Introduction\n\nHave you always wanted to run ...,3.500000,iRobot\n3.5,"Bedford, MA",1990,Consumer Electronics & Appliances Stores
8,Staff Data Scientist - Analytics,Intuit is seeking a Staff Data Scientist to co...,4.400000,Intuit - Data\n4.4,"San Diego, CA",1983,Computer Hardware & Software
9,Data Scientist,Ready to write the best chapter of your career...,3.600000,XSELL Technologies\n3.6,"Chicago, IL",2014,NaN

### **Task 1.2 (Handling Blanks)**
The `Industry` column has several completely blank or empty cells. Fill these missing values with the string text `"Unknown"`.

In [99]:
# Write your solution for Task 1.2 here
gd['Industry'] = gd['Industry'].replace (-1, np.nan)
gd['Industry'] = gd['Industry'].fillna("Unknown")
gd.head(6)

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.100000,Healthfirst\n3.1,"New York, NY",1993,Insurance Carriers
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.200000,ManTech\n4.2,"Chantilly, VA",1968,Research & Development
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,3.885766,Analysis Group\n3.8,"Boston, MA",1981,Consulting
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.500000,INFICON\n3.5,"Newton, MA",2000,Electrical & Electronic Manufacturing
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.900000,Affinity Solutions\n2.9,"New York, NY",1998,Advertising & Marketing
5,Data Scientist,About Us:\n\nHeadquartered in beautiful Santa ...,4.200000,HG Insights\n4.2,"Santa Barbara, CA",2010,Unknown

### **Task 1.3 (Data Filtering)**
A few rows contain placeholder or invalid values in the `Founded` year column (values less than or equal to `0`). **Filter the dataset** to permanently remove these invalid rows.

In [112]:
# Write your solution for Task 1.3 here
gd['Founded'] = gd['Founded'].replace(-1, np.nan)
gd.dropna(subset = ['Founded'], inplace = True)
display(gd)

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry,Job_City,Job_State,Industry_Avg_Rating,Rating_Above_Industry_Avg
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.100000,Healthfirst\n3.1,"New York, NY",1993.0,Insurance Carriers,New York,NY,3.792322,-0.692322
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.200000,ManTech\n4.2,"Chantilly, VA",1968.0,Research & Development,Chantilly,VA,3.904471,0.295529
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,3.885766,Analysis Group\n3.8,"Boston, MA",1981.0,Consulting,Boston,MA,3.874531,0.011235
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.500000,INFICON\n3.5,"Newton, MA",2000.0,Electrical & Electronic Manufacturing,Newton,MA,3.692883,-0.192883
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.900000,Affinity Solutions\n2.9,"New York, NY",1998.0,Advertising & Marketing,New York,NY,3.731300,-0.831300
...,...,...,...,...,...,...,...,...,...,...,...
663,Data Scientist,Job Description\nEducation and Experience:\nAt...,4.100000,A-Line Staffing Solutions\n4.1,"Durham, NC",2004.0,Staffing & Outsourcing,Durham,NC,4.059312,0.040688
665,Data Scientist,Criterion Systems seeks a Data Scientist to su...,3.800000,"Criterion Systems, Inc.\n3.8","Vienna, VA",2005.0,IT Services,Vienna,VA,4.114797,-0.314797
666,Data Scientist,About Foundation Medicine:\n\nFoundation Medic...,4.000000,Foundation Medicine\n4.0,"Boston, MA",2010.0,Biotech & Pharmaceuticals,Boston,MA,3.694938,0.305062
667,Data Scientist,Summary\n\nWe’re looking for a data scientist ...,3.885766,TRANZACT\n3.6,"Fort Lee, NJ",1989.0,Advertising & Marketing,Fort Lee,NJ,3.731300,0.154466
671,Data Scientist,Description\n\nThe Data Scientist will be part...,2.700000,1-800-Flowers\n2.7,"New York, NY",1976.0,Wholesale,New York,NY,2.633333,0.066667

## Part 2: String Manipulations (20 Points)

### **Task 2.1 (Location Splitting)**
The `Location` column lists locations as `"City, State"` (e.g., `"Chicago, IL"` or `"Austin, TX"`). Split this column into two separate, brand-new columns: `Job_City` and `Job_State`.

In [101]:
# Write your solution for Task 2.1 here
gd['Job_City'] = gd['Location'].str.split(',', expand=True)[0]
gd['Job_State'] = gd['Location'].str.split(',', expand=True)[1]
gd.head()

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry,Job_City,Job_State
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.100000,Healthfirst\n3.1,"New York, NY",1993.0,Insurance Carriers,New York,NY
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.200000,ManTech\n4.2,"Chantilly, VA",1968.0,Research & Development,Chantilly,VA
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,3.885766,Analysis Group\n3.8,"Boston, MA",1981.0,Consulting,Boston,MA
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.500000,INFICON\n3.5,"Newton, MA",2000.0,Electrical & Electronic Manufacturing,Newton,MA
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.900000,Affinity Solutions\n2.9,"New York, NY",1998.0,Advertising & Marketing,New York,NY

### **Task 2.2 (Whitespace Cleaning)**
The new `Job_State` column might contain accidental leading or trailing empty spaces from the split. Apply a string cleaning function (like `.str.strip()`) to ensure no accidental spaces remain.

In [102]:
# Write your solution for Task 2.2 here
gd['Job_State'] = gd['Job_State'].str.strip()
gd.head()

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry,Job_City,Job_State
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.100000,Healthfirst\n3.1,"New York, NY",1993.0,Insurance Carriers,New York,NY
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.200000,ManTech\n4.2,"Chantilly, VA",1968.0,Research & Development,Chantilly,VA
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,3.885766,Analysis Group\n3.8,"Boston, MA",1981.0,Consulting,Boston,MA
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.500000,INFICON\n3.5,"Newton, MA",2000.0,Electrical & Electronic Manufacturing,Newton,MA
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.900000,Affinity Solutions\n2.9,"New York, NY",1998.0,Advertising & Marketing,New York,NY

## Part 3: Feature Engineering with Grouped Transformations (20 Points)

### **Task 3.1 (Grouped Transform)**
The recruiting team wants to identify jobs that offer a higher-than-average user rating relative to their specific field. 

Use `.groupby()` and `.transform()` to calculate the **average (mean) rating for each `Industry`**, broadcasting it back as a new column named `Industry_Avg_Rating`. Then, create a column called `Rating_Above_Industry_Avg` by subtracting `Industry_Avg_Rating` from the job's original `Rating`.

In [114]:
# Write your solution for Task 3.1 here
gd['Industry_Avg_Rating'] = gd.groupby('Industry')['Rating'].transform("mean")

gd['Rating_Above_Industry_Avg'] = gd['Rating'] - gd['Industry_Avg_Rating']
gd.head()

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry,Job_City,Job_State,Industry_Avg_Rating,Rating_Above_Industry_Avg
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.100000,Healthfirst\n3.1,"New York, NY",1993.0,Insurance Carriers,New York,NY,3.792322,-0.692322
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.200000,ManTech\n4.2,"Chantilly, VA",1968.0,Research & Development,Chantilly,VA,3.904471,0.295529
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,3.885766,Analysis Group\n3.8,"Boston, MA",1981.0,Consulting,Boston,MA,3.876204,0.009562
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.500000,INFICON\n3.5,"Newton, MA",2000.0,Electrical & Electronic Manufacturing,Newton,MA,3.692883,-0.192883
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.900000,Affinity Solutions\n2.9,"New York, NY",1998.0,Advertising & Marketing,New York,NY,3.681963,-0.781963

## Part 4: Merging & Aggregating Data (30 Points)

### **Task 4.1 (Dataset Merging)**
You are provided a second, clean reference CSV file named `state_regions.csv` which contains two columns: `State_Abbreviation` and `US_Region` (e.g., *IL, Midwest*). 

Perform a **left merge** to add the `US_Region` column to your main job postings dataframe by matching your new `Job_State` column with the reference file's `State_Abbreviation` column.

In [104]:
# Write your solution for Task 4.1 here
gd_regions = gd.merge(
    state_regions_df[['State_Abbreviation', 'US_Region']],
    how='left',
    left_on='Job_State',
    right_on='State_Abbreviation'
).drop(columns='State_Abbreviation')

### **Task 4.2 (Grouped Aggregation)**
Group your newly merged dataframe by the `US_Region` column. For each region, calculate:
1. The **total count** of job postings in that region.
2. The **average (mean)** employee `Rating` in that region.

In [105]:
# Write your solution for Task 4.2 here
job_count = gd_regions.groupby('US_Region')['US_Region'].agg('count')
gd_regions.groupby('US_Region')['Rating'].agg('mean')

US_Region
Midwest      3.497628
Northeast    3.950259
South        3.942494
West         3.889989
Name: Rating, dtype: float64

### **Task 4.3 (Data Export)**
Save your final, aggregated summary table from Task 4.2 to a new file named `regional_job_summary.csv`.

In [106]:
# Write your solution for Task 4.3 here
gd.to_csv('regional_job_summary.csv', index=False)